### ISSUE TITLE
License note

### ISSUE THREAD

**Issue by harry-wood** [rory/openstreetmap-bendy-roads#2]
I like the bendy roads visualisation. I was hunting for interesting images like this to have as the OpenStreetMap image of the week. I would do so with a link to the details you written here: http://www.technomancy.org/openstreetmap/bendy-roads/

Thanks for including license info on there, which is usefully very clear about rights to the visualisation image. Can I suggest you add a sentence there saying something like *"Made using open licensed (ODbL) data from OpenStreetMap"* 

I know it's obvious and completely self-evident in a way, but since you have special "License" heading, it's worth mentioning there.

**Comment by rory** [comment]
Done! :smile: Thanks.

**Comment by harry-wood** [comment]
It's "image of the week" this week by the way ( http://wiki.osm.org )  :-)
